Repository LearnWithCommunity/support, pull requests merged in 2021-12, with the labels that each got.

#3 docs(governance): code of conduct
  CODE_OF_CONDUCT.md
Labels: ⭐ goal: addition, 📄 aspect: text, 🟩 priority: low, 🔢 points: 2

#8 feat: add prettier
  .github/workflows/format.yml
  .github/workflows/invitation.yml
  CODE_OF_CONDUCT.md
  README.md
Labels: ⭐ goal: addition, 🟩 priority: low, 🤖 aspect: dx, 🔢 points: 3

#9 fix: label not found
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/ideas.yml
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: 🛠 goal: fix, 🟩 priority: low, 🤖 aspect: dx, 🔢 points: 1

#10 feat: contributing file
  CONTRIBUTING.md
Labels: ⭐ goal: addition, 📄 aspect: text, 🤖 aspect: dx, 🟨 priority: medium, 🔢 points: 2

#21 fix: add contact links in the configuration template
  .github/ISSUE_TEMPLATE/config.yml
Labels: ⭐ goal: addition

#24 docs: improve readme
  README.md
Labels: ✨ goal: improvement

#29 docs: improve the issue templates/forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/ideas.yml
  .github/ISSUE_TEMPLATE/invitation.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: 📄 aspect: text
